# Generated by Django 5.2.3 on 2025-06-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrique',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sousrubrique',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
