# Generated by Django 5.2.3 on 2025-06-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rubrique_slug_sousrubrique_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrique',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sousrubrique',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
